services:
  api-server:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - pdf-processor
    environment:
      - APP_SERVICES_PDFPROCESSOR_HOST=pdf-processor
      - APP_SERVICES_PDFPROCESSOR_PORT=50051
      - APP_LOGGING_LEVEL=info
    volumes:
      - ./api-server:/app/src
      - ./api-server/script:/app/script
      - ./data:/app/data
    restart: unless-stopped

  pdf-processor:
    build: ./pdf-processor
    volumes:
      - ./pdf-processor/src:/app/src
      - ./data:/app/data
      - ./.cache/huggingface:/root/.cache/huggingface:rw  # Added :rw for explicit read-write permissions
    environment:
      - LOG_LEVEL=DEBUG
      - ENABLE_PII_DETECTION=true
      - ENABLE_OCR=true
      - TRANSFORMERS_CACHE=/root/.cache/huggingface
      - TRANSFORMERS_OFFLINE=1  # Force offline mode
      - HF_HUB_OFFLINE=1  # Prevent online checks
    ports:
      - "50051:50051"
    restart: unless-stopped

  # This will be added later when you implement full document storage
  # minio:
  #   image: minio/minio
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   volumes:
  #     - ./data/minio:/data
  #   environment:
  #     - MINIO_ROOT_USER=minioadmin
  #     - MINIO_ROOT_PASSWORD=minioadmin
  #   command: server /data --console-address ":9001"
  #   restart: unless-stopped

  # This will be added later for translation services
  # translation-service:
  #   build: ./translation-service
  #   volumes:
  #     - ./translation-service:/app
  #     - ./data:/app/data
  #   ports:
  #     - "50052:50052"
  #   environment:
  #     - MODEL_PATH=/app/models
  #   restart: unless-stopped